AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon Cognito User Pool with Hosted UI and Custom Domain CloudFormation Stack

Resources:
  MyUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: CognitoUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true

  MyUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: MyCognitoAppClient
      UserPoolId: !Ref MyUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
        - USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      CallbackURLs:
        - https://example.com/callback
      LogoutURLs:
        - https://example.com/logout

  MyUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: mydomainthaer
      UserPoolId: !Ref MyUserPool

Outputs:
  UserPoolId:
    Description: The ID of the created Amazon Cognito User Pool.
    Value: !Ref MyUserPool

  UserPoolClientId:
    Description: The ID of the created Amazon Cognito User Pool Client (App Client).
    Value: !Ref MyUserPoolClient

  UserPoolDomain:
    Description: The custom domain for the Amazon Cognito Hosted UI.
    Value: !Ref MyUserPoolDomain
