AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Dashboard Example

Resources:
  MyCloudWatchDashboard:
    Type: 'AWS::CloudWatch::Dashboard'
    Properties:
      DashboardName: ArunaCustomDashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/EC2", "CPUUtilization", "InstanceId", "i-0279ff403135dd46d"]
                ],
                "view": "timeSeries",
                "region": "ap-south-1",
                "title": "EC2 CPU Utilization"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/EC2", "NetworkIn", "InstanceId", "i-0279ff403135dd46d"],
                  ["AWS/EC2", "NetworkOut", "InstanceId", "i-0279ff403135dd46d"]
                ],
                "view": "timeSeries",
                "region": "ap-south-1",
                "title": "EC2 Network Traffic"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 12,
              "width": 12,
              "height": 6,
              "properties": {
                "view": "singleValue",
                "stacked": false,
                "region": "ap-south-1",
                "period": 900,
                "stat": "Average",
                "title": "Number of Objects in teambucketsonix",
                "metrics": [
                  ["AWS/S3", "NumberOfObjects", "StorageType", "AllStorageTypes", "BucketName", "teambucketsonix", { "region": "ap-south-1" }]
                ],
                "start": "-PT168H",
                "end": "P0D",
                "setPeriodToTimeRange": true
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 18,
              "width": 12,
              "height": 6,
              "properties": {
                "view": "singleValue",
                "stacked": false,
                "region": "ap-south-1",
                "period": 900,
                "stat": "Average",
                "title": "Number of Objects in cf-templates-15s5bskype21r-ap-south-1",
                "metrics": [
                  ["AWS/S3", "NumberOfObjects", "StorageType", "AllStorageTypes", "BucketName", "cf-templates-15s5bskype21r-ap-south-1", { "region": "ap-south-1" }]
                ],
                "start": "-PT168H",
                "end": "P0D",
                "setPeriodToTimeRange": true
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 30,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/S3", "BucketSizeBytes", "StorageType", "StandardStorage", "BucketName", "teambucketsonix", { "region": "ap-south-1" }]
                ],
                "view": "singleValue",
                "stacked": false,
                "region": "ap-south-1",
                "period": 86400,
                "stat": "Average",
                "title": "Bucket Size for teambucketsonix"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 36,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/S3", "BucketSizeBytes", "StorageType", "StandardStorage", "BucketName", "cf-templates-15s5bskype21r-ap-south-1", { "region": "ap-south-1" }]
                ],
                "view": "singleValue",
                "stacked": false,
                "region": "ap-south-1",
                "period": 86400,
                "stat": "Average",
                "title": "Bucket Size for cf-templates-15s5bskype21r-ap-south-1"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 42,
              "width": 12,
              "height": 6,
              "properties": {
                "view": "singleValue",
                "stacked": false,
                "metrics": [
                  ["AWS/Cognito", "SignInSuccesses", "UserPool", "ap-south-1_rRTVTNWDU", "UserPoolClient", "691ovgsdfp9j6nllqartfk7g57", { "region": "ap-south-1" }]
                ],
                "region": "ap-south-1",
                "period": 300,
                "title": "Cognito SignIn Successes"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 48,
              "width": 12,
              "height": 6,
              "properties": {
                "view": "singleValue",
                "stacked": true,
                "metrics": [
                  ["AWS/Cognito", "SignUpSuccesses", "UserPool", "ap-south-1_rRTVTNWDU", "UserPoolClient", "691ovgsdfp9j6nllqartfk7g57", { "region": "ap-south-1" }]
                ],
                "region": "ap-south-1",
                "period": 300,
                "title": "Cognito SignUp Successes"
              }
            }
          ]
        }
